services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '5173:80'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./go-server
    container_name: backend
    ports:
      - '8080:8080'
    networks:
      - app-network

networks:
  app-network:
